name: Publish to GitHub and Crates.io
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
env:
  GIT_TAG: ${{ github.ref_name }}
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ env.GIT_TAG }}
      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Authenticate with Crates.io
        uses: rust-lang/crates-io-auth-action@v1
        id: auth
      - name: Publish to Crates.io
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: ${{ github.repository }}
          target: env-build
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Run Docker image
        run: docker run --name temp ${{ github.repository }}
      - name: Copy Docker container artifacts
        run: |
          mkdir -p bin
          docker cp temp:/srv/luavisors-glibc-amd64 ./bin/luavisors-glibc-amd64
          docker cp temp:/srv/SHA256SUMS ./bin/SHA256SUMS
      - name: Upload the latest artifacts to releases
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "bin/*"
          makeLatest: true
          name: ${{ env.GIT_TAG }}
          tag: ${{ env.GIT_TAG }}
